### ISSUE TITLE
html_to_pdf/SwiftHtmlToPdfPlugin.swift:25: Fatal error: Unexpectedly found nil while unwrapping an Optional value

### ISSUE THREAD

**Issue by Samnangsokhorn** [penkzhou/plugin_html_to_pdf#12]
<img width="1021" height="533" alt="Image" src="https://github.com/user-attachments/assets/63028f28-b35e-4a3b-b495-15a19cd67a70" />

 I have an old project which was created may be 2 and half years ago. There is an issue after upgrading flutter version to 3.41.6. When starting generate PDF using this plugin on IOS platform (Only IOS) it crashes.

Platform : IOS
Flutter SDK Version : 3.41.6
html_to_pdf:  ^0.8.1
